"""MRC Configuration Manager for ASSella and SLSsteam Lua Plugins.

Provides baseline controls for Manifest Request Code (MRC) resolution hierarchy,
provider priority, and race/timeout parameters. Synchronizes configuration between
ASSella QSettings and SLSsteam in ~/.config/SLSsteam/mrc_config.lua / mrc_config.json.
"""

import json
import logging
import os
from pathlib import Path
from typing import Any, Dict

from utils.settings import get_settings

logger = logging.getLogger(__name__)

# Known MRC Provider URL mappings
MRC_PROVIDER_URLS = {
    "wudrm": "http://gmrc.wudrm.com/manifest/",
    "manifestdex": "https://manifest.manifestdex.com/",
}

MRC_PROVIDER_HEADERS = {
    "wudrm": None,
    "manifestdex": ['"User-Agent: ManifestDeX/1.0"'],
}


def get_sls_config_dir() -> Path:
    """Return the SLSsteam configuration directory."""
    return Path(os.path.expanduser("~/.config/SLSsteam"))


def get_mrc_lua_config_path() -> Path:
    """Return the path to mrc_config.lua inside SLSsteam directory."""
    return get_sls_config_dir() / "mrc_config.lua"


def get_mrc_json_config_path() -> Path:
    """Return the path to mrc_config.json inside SLSsteam directory."""
    return get_sls_config_dir() / "mrc_config.json"


class MRCConfigManager:
    """Manages reading, writing, and synchronizing MRC provider configuration."""

    DEFAULT_CONFIG = {
        "authority": "wudrm",
        "rescue": "manifestdex",
        "full_timeout_ms": 2000,
        "probe_timeout_ms": 700,
        "probe_timeouts_to_mark_down": 2,
        "down_ttl_ms": 60000,
        "provisional_ttl_s": 300,
        "fail_ttl_s": 120,
    }

    @classmethod
    def load_config(cls) -> Dict[str, Any]:
        """Load current MRC configuration from QSettings with safe fallbacks."""
        settings = get_settings()
        cfg = {}
        cfg["authority"] = settings.value("mrc_authority", cls.DEFAULT_CONFIG["authority"], type=str)
        cfg["rescue"] = settings.value("mrc_rescue", cls.DEFAULT_CONFIG["rescue"], type=str)
        # Ensure valid providers
        if cfg["authority"] not in MRC_PROVIDER_URLS:
            cfg["authority"] = cls.DEFAULT_CONFIG["authority"]
        if cfg["rescue"] not in MRC_PROVIDER_URLS:
            cfg["rescue"] = cls.DEFAULT_CONFIG["rescue"]
        cfg["full_timeout_ms"] = settings.value("mrc_full_timeout_ms", cls.DEFAULT_CONFIG["full_timeout_ms"], type=int)
        cfg["probe_timeout_ms"] = settings.value("mrc_probe_timeout_ms", cls.DEFAULT_CONFIG["probe_timeout_ms"], type=int)
        cfg["probe_timeouts_to_mark_down"] = settings.value("mrc_probe_timeouts_to_mark_down", cls.DEFAULT_CONFIG["probe_timeouts_to_mark_down"], type=int)
        cfg["down_ttl_ms"] = settings.value("mrc_down_ttl_ms", cls.DEFAULT_CONFIG["down_ttl_ms"], type=int)
        cfg["provisional_ttl_s"] = settings.value("mrc_provisional_ttl_s", cls.DEFAULT_CONFIG["provisional_ttl_s"], type=int)
        cfg["fail_ttl_s"] = settings.value("mrc_fail_ttl_s", cls.DEFAULT_CONFIG["fail_ttl_s"], type=int)
        return cfg

    @classmethod
    def save_config(cls, cfg: Dict[str, Any]) -> None:
        """Persist MRC configuration to QSettings."""
        settings = get_settings()
        for k, v in cfg.items():
            settings.setValue(f"mrc_{k}", v)
        settings.sync()

    @classmethod
    def sync_to_slssteam(cls, cfg: Dict[str, Any]) -> bool:
        """Write configuration to ~/.config/SLSsteam/mrc_config.lua and mrc_config.json in-place."""
        try:
            sls_dir = get_sls_config_dir()
            sls_dir.mkdir(parents=True, exist_ok=True)

            auth_name = cfg.get("authority", "wudrm")
            rescue_name = cfg.get("rescue", "manifestdex")
            auth_url = MRC_PROVIDER_URLS.get(auth_name, MRC_PROVIDER_URLS["wudrm"])
            rescue_url = MRC_PROVIDER_URLS.get(rescue_name, MRC_PROVIDER_URLS["manifestdex"])

            rescue_headers = MRC_PROVIDER_HEADERS.get(rescue_name)
            if rescue_headers:
                headers_lua = "{ " + ", ".join(rescue_headers) + " }"
            else:
                headers_lua = "nil"

            # Render Lua configuration table
            lua_content = f"""-- Auto-generated by ASSella Settings.
-- Manifest Request Code (MRC) provider controls and race parameters.
return {{
    authority = {{
        name = "{auth_name}",
        url = "{auth_url}",
        headers = nil,
    }},
    rescue = {{
        name = "{rescue_name}",
        url = "{rescue_url}",
        headers = {headers_lua},
    }},
    tuning = {{
        FULL_MS = {int(cfg.get('full_timeout_ms', 2000))},
        PROBE_MS = {int(cfg.get('probe_timeout_ms', 700))},
        PROBE_TIMEOUTS_TO_MARK_DOWN = {int(cfg.get('probe_timeouts_to_mark_down', 2))},
        DOWN_TTL_MS = {int(cfg.get('down_ttl_ms', 60000))},
        PROVISIONAL_TTL = {int(cfg.get('provisional_ttl_s', 300))},
        FAIL_TTL = {int(cfg.get('fail_ttl_s', 120))},
    }}
}}
"""
            # Preserve system inode by opening existing file in-place with 'w'
            lua_path = get_mrc_lua_config_path()
            with open(lua_path, "w", encoding="utf-8") as f:
                f.write(lua_content)

            # Also write JSON companion for easy inspection
            json_path = get_mrc_json_config_path()
            with open(json_path, "w", encoding="utf-8") as f:
                json.dump(cfg, f, indent=2)

            logger.info(f"[MRCConfigManager] Successfully synced MRC config to {lua_path}")
            return True
        except Exception as e:
            logger.error(f"[MRCConfigManager] Failed syncing MRC config to SLSsteam: {e}")
            return False
