"""Shared Lua parsing helpers.

Steam "unlock" Lua manifests (as produced by Hubcap) mix live statements with
commented-out ones. Commented statements are used deliberately by the generator
to disable depots it cannot serve, e.g.::

    -- addappid(5136471, 1, "MISSING_KEY") -- Depot 5136471 (no key available)
    -- addappid(1350872) -- Depot 1350872 (empty depot)

Naive ``re.finditer(r"addappid\\(...)")`` matches those too, which injects
disabled depots into parsed metadata as either fake-keyed depots or, worse, as
DLC AppIDs (an ``addappid(<id>)`` with no key argument is indistinguishable from
a license-only DLC). That pollution then flows into AdditionalApps /
AdditionalDepots / DecryptionKeys.

Every Lua scan in the codebase should therefore go through
:func:`iter_live_matches`, which skips matches that start inside a Lua comment.
"""

import bisect
import re
from typing import Any, Iterator, List, Pattern, Tuple, Union

__all__ = [
    "comment_spans",
    "iter_live_matches",
    "find_live",
    "MISSING_KEY_SENTINEL",
    "is_placeholder_key",
]

# Hubcap's literal marker for "this depot has no obtainable key". It is not a
# key; treating it as one produces DepotWithoutKey failures downstream.
MISSING_KEY_SENTINEL = "MISSING_KEY"

# Values that are obviously not AES keys. A handful of third-party manifests use
# short/placeholder values; those are still honoured (they are live statements),
# but callers that require a real 64-hex key can screen them out.
_PLACEHOLDER_KEYS = {MISSING_KEY_SENTINEL, "", "0", "NULL", "NONE", "UNKNOWN"}

_HEX64 = re.compile(r"^[a-fA-F0-9]{64}$")


def comment_spans(content: str) -> List[Tuple[int, int]]:
    """Return ``(start, end)`` index pairs for every Lua line comment.

    Handles ``--`` line comments only (which is all Hubcap emits) and respects
    single/double quoted strings so a ``--`` inside an argument is not treated as
    a comment. Block comments (``--[[ ]]``) are not generated by the manifest
    tools and are deliberately not handled.
    """
    spans: List[Tuple[int, int]] = []
    length = len(content)
    index = 0
    quote: Union[str, None] = None

    while index < length:
        char = content[index]
        if quote is not None:
            if char == "\\" and quote == '"':
                # Skip the escaped character inside a double-quoted string.
                index += 2
                continue
            if char == quote:
                quote = None
        elif char in ("'", '"'):
            quote = char
        elif char == "-" and content.startswith("--", index):
            end = content.find("\n", index)
            if end == -1:
                end = length
            spans.append((index, end))
            index = end
            continue
        index += 1

    return spans


def _normalize_args(arg1: Any, arg2: Any) -> Tuple[str, Union[str, Pattern]]:
    """Tolerate both (content, pattern) and (pattern, content) calling conventions."""
    if isinstance(arg1, Pattern):
        return str(arg2), arg1
    if isinstance(arg2, Pattern):
        return str(arg1), arg2
    s1, s2 = str(arg1), str(arg2)
    if ("\n" in s2 or "--" in s2) and ("\n" not in s1 or len(s2) > len(s1) * 2):
        return s2, s1
    return s1, s2


def iter_live_matches(
    content: str,
    pattern: Union[str, Pattern],
    flags: int = 0,
) -> Iterator[re.Match]:
    """Yield ``re.finditer`` matches that are NOT inside a Lua line comment.

    Drop-in replacement for ``re.finditer`` when scanning Hubcap-style Lua.
    Tolerates both ``(content, pattern)`` and standard ``(pattern, content)`` argument order.
    """
    content, pattern = _normalize_args(content, pattern)
    spans = comment_spans(content)
    if not spans:
        yield from re.finditer(pattern, content, flags)
        return

    # Fast membership test: comment spans are sorted and non-overlapping.
    starts = [start for start, _ in spans]
    for match in re.finditer(pattern, content, flags):
        position = match.start()
        slot = bisect.bisect_right(starts, position) - 1
        if slot >= 0 and position < spans[slot][1]:
            continue
        yield match


def find_live(
    content: str,
    pattern: Union[str, Pattern],
    flags: int = 0,
) -> "re.Match | None":
    """Return the first live (non-commented) match, or ``None``."""
    content, pattern = _normalize_args(content, pattern)
    for match in iter_live_matches(content, pattern, flags):
        return match
    return None


def is_placeholder_key(value: str) -> bool:
    """True when ``value`` is a generator sentinel rather than a usable AES key."""
    text = str(value).strip().strip("\"'")
    if not text:
        return True
    return text.upper() in _PLACEHOLDER_KEYS


def is_real_key(value: str) -> bool:
    """True only for a well-formed 64-character hex AES key."""
    return bool(_HEX64.match(str(value).strip()))