"""Shared Lua parsing helpers.

Steam "unlock" Lua manifests (as produced by Hubcap) mix live statements with
commented-out ones. Commented statements are used deliberately by the generator
to disable depots it cannot serve, e.g.::

    -- addappid(5136471, 1, "MISSING_KEY") -- Depot 5136471 (no key available)
    -- addappid(1350872) -- Depot 1350872 (empty depot)

Naive ``re.finditer(r"addappid\\(...)")`` matches those too, which injects
disabled depots into parsed metadata as either fake-keyed depots or, worse, as
DLC AppIDs (an ``addappid(<id>)`` with no key argument is indistinguishable from
a license-only DLC). That pollution then flows into AdditionalApps /
AdditionalDepots / DecryptionKeys.

Every Lua scan in the codebase should therefore go through
:func:`iter_live_matches`, which skips matches that start inside a Lua comment.
"""

import bisect
import re
from typing import Any, Iterator, List, Optional, Pattern, Tuple, Union

__all__ = [
    "comment_spans",
    "iter_live_matches",
    "find_live",
    "MISSING_KEY_SENTINEL",
    "is_placeholder_key",
    "is_real_key",
    "smart_merge_lua",
    "coerce_depot_id",
    "coerce_manifest_gid",
    "extract_token",
]

# Hubcap's literal marker for "this depot has no obtainable key". It is not a
# key; treating it as one produces DepotWithoutKey failures downstream.
MISSING_KEY_SENTINEL = "MISSING_KEY"

# Values that are obviously not AES keys. A handful of third-party manifests use
# short/placeholder values; those are still honoured (they are live statements),
# but callers that require a real 64-hex key can screen them out.
_PLACEHOLDER_KEYS = {MISSING_KEY_SENTINEL, "", "0", "NULL", "NONE", "UNKNOWN"}

_HEX64 = re.compile(r"^[a-fA-F0-9]{64}$")


def comment_spans(content: str) -> List[Tuple[int, int]]:
    """Return ``(start, end)`` index pairs for every Lua line comment.

    Handles ``--`` line comments only (which is all Hubcap emits) and respects
    single/double quoted strings so a ``--`` inside an argument is not treated as
    a comment. Block comments (``--[[ ]]``) are not generated by the manifest
    tools and are deliberately not handled.
    """
    spans: List[Tuple[int, int]] = []
    length = len(content)
    index = 0
    quote: Union[str, None] = None

    while index < length:
        char = content[index]
        if quote is not None:
            if char == "\\" and quote == '"':
                # Skip the escaped character inside a double-quoted string.
                index += 2
                continue
            if char == quote:
                quote = None
        elif char in ("'", '"'):
            quote = char
        elif char == "-" and content.startswith("--", index):
            end = content.find("\n", index)
            if end == -1:
                end = length
            spans.append((index, end))
            index = end
            continue
        index += 1

    return spans


def _normalize_args(arg1: Any, arg2: Any) -> Tuple[str, Union[str, Pattern]]:
    """Tolerate both (content, pattern) and (pattern, content) calling conventions."""
    if isinstance(arg1, Pattern):
        return str(arg2), arg1
    if isinstance(arg2, Pattern):
        return str(arg1), arg2
    s1, s2 = str(arg1), str(arg2)
    if ("\n" in s2 or "--" in s2) and ("\n" not in s1 or len(s2) > len(s1) * 2):
        return s2, s1
    return s1, s2


def iter_live_matches(
    content: str,
    pattern: Union[str, Pattern],
    flags: int = 0,
) -> Iterator[re.Match]:
    """Yield ``re.finditer`` matches that are NOT inside a Lua line comment.

    Drop-in replacement for ``re.finditer`` when scanning Hubcap-style Lua.
    Tolerates both ``(content, pattern)`` and standard ``(pattern, content)`` argument order.
    """
    content, pattern = _normalize_args(content, pattern)
    spans = comment_spans(content)
    if not spans:
        yield from re.finditer(pattern, content, flags)
        return

    # Fast membership test: comment spans are sorted and non-overlapping.
    starts = [start for start, _ in spans]
    for match in re.finditer(pattern, content, flags):
        position = match.start()
        slot = bisect.bisect_right(starts, position) - 1
        if slot >= 0 and position < spans[slot][1]:
            continue
        yield match


def find_live(
    content: str,
    pattern: Union[str, Pattern],
    flags: int = 0,
) -> "re.Match | None":
    """Return the first live (non-commented) match, or ``None``."""
    content, pattern = _normalize_args(content, pattern)
    for match in iter_live_matches(content, pattern, flags):
        return match
    return None


def is_placeholder_key(value: str) -> bool:
    """True when ``value`` is a generator sentinel rather than a usable AES key."""
    text = str(value).strip().strip("\"'")
    if not text:
        return True
    return text.upper() in _PLACEHOLDER_KEYS


def is_real_key(value: str) -> bool:
    """True only for a well-formed 64-character hex AES key."""
    return bool(_HEX64.match(str(value).strip()))


def smart_merge_lua(
    new_lua: str,
    cached_lua: str,
    extra_depot_keys: Union[dict, None] = None,
) -> str:
    """
    Intelligently merges a newly imported Lua manifest with a previously cached Lua.

    Guarantees:
    - If the newly imported Lua lacks keys for certain depots (or has MISSING_KEY sentinels)
      but the cached Lua (or extra_depot_keys) contains valid AES keys, those valid keys are preserved/restored.
    - If the newly imported Lua supplies new valid keys, updated manifests, or new branches,
      they take precedence.
    - Depots present only in the cached Lua are preserved so partial drops do not drop existing DLCs.
    - Tokens (addtoken) are preserved if present in either manifest.
    """
    cached_keys: dict[str, str] = {}
    cached_manifests: dict[str, str] = {}
    cached_token: Union[Tuple[str, str], None] = None
    cached_appids: set[str] = set()

    if extra_depot_keys:
        for did, k in extra_depot_keys.items():
            if k and not is_placeholder_key(k):
                cached_keys[str(did)] = str(k).strip("\"'")

    if cached_lua:
        for m in iter_live_matches(
            cached_lua,
            r'addappid\(\s*(\d+)\s*(?:,\s*(\d+))?(?:,\s*["\']([^"\']+)["\'])?',
            re.IGNORECASE,
        ):
            did = m.group(1)
            cached_appids.add(did)
            k = m.group(3)
            if k and not is_placeholder_key(k):
                cached_keys[did] = k

        for m in iter_live_matches(
            cached_lua,
            r'setManifestid\(\s*(\d+)\s*,\s*["\']([^"\']+)["\']',
            re.IGNORECASE,
        ):
            cached_manifests[m.group(1)] = m.group(2)

        m_tok = find_live(
            cached_lua,
            r'addtoken\(\s*(\d+)\s*,\s*["\']([^"\']+)["\']',
            re.IGNORECASE,
        )
        if m_tok:
            cached_token = (m_tok.group(1), m_tok.group(2))

    new_appids: set[str] = set()
    new_manifest_dids: set[str] = set()
    merged_lines: List[str] = []

    for line in new_lua.splitlines():
        # Match addappid live or commented
        m_app = re.search(
            r'(--\s*)?addappid\(\s*(\d+)\s*(?:,\s*(\d+))?(?:,\s*["\']([^"\']*)["\'])?\s*\)(.*)',
            line,
            re.IGNORECASE,
        )
        if m_app:
            is_comm = bool(m_app.group(1))
            did = m_app.group(2)
            flag = m_app.group(3) or "1"
            key = m_app.group(4) or ""
            tail = m_app.group(5) or ""
            new_appids.add(did)

            # If key is missing or a generator sentinel, check if we have a valid key in cache
            if is_placeholder_key(key) or not key:
                if did in cached_keys:
                    key = cached_keys[did]
                    is_comm = False  # Uncomment line now that key is restored!
                    if "(no key available)" in tail:
                        tail = tail.replace("(no key available)", "(restored from cache)")

            prefix = "-- " if is_comm else ""
            key_part = f', "{key}"' if key else ""
            merged_lines.append(f"{prefix}addappid({did}, {flag}{key_part}){tail}")
            continue

        m_mf = re.search(
            r'setManifestid\(\s*(\d+)\s*,\s*["\']([^"\']+)["\']',
            line,
            re.IGNORECASE,
        )
        if m_mf:
            new_manifest_dids.add(m_mf.group(1))

        merged_lines.append(line)

    # Preserve cached addtoken if newly imported Lua didn't have one.
    # Must be comment-aware: a commented-out addtoken must not suppress the
    # cached live one.
    has_token = has_live_token(new_lua)
    if not has_token and cached_token:
        merged_lines.append(f'addtoken({cached_token[0]}, "{cached_token[1]}")')

    # Preserve any additional depots from cache not present in the new Lua
    missing_depots = [did for did in cached_appids if did not in new_appids]
    if missing_depots:
        merged_lines.append("")
        merged_lines.append("-- Depots preserved from previous cache")
        for did in missing_depots:
            k = cached_keys.get(did)
            if k:
                merged_lines.append(f'addappid({did}, 1, "{k}")')
            else:
                merged_lines.append(f"addappid({did})")
            if did in cached_manifests and did not in new_manifest_dids:
                merged_lines.append(f'setManifestid({did}, "{cached_manifests[did]}")')

    return "\n".join(merged_lines)

# ---------------------------------------------------------------------------
# Boundary validation
#
# Every identifier below originates from a remote Hubcap Lua (or a zip member
# name) and is later interpolated into filesystem paths, config.yaml entries and
# Steam depotcache filenames. A crafted value such as
# ``addappid(../../../../home/user/.bashrc, 1)`` is matched happily by the
# generic addappid regex, so each identifier must be validated before it is
# allowed to leave the parser.
# ---------------------------------------------------------------------------

# Real Steam AppIDs/DepotIDs are 4-11 digits in practice; allow 1-12 to stay
# tolerant of oddities while still rejecting path and injection payloads.
_DEPOT_ID_RE = re.compile(r"^[0-9]{1,12}$")

# Manifest GIDs are large unsigned integers (observed up to ~7.3e18), always
# numeric. Reject anything else before it can become a path segment.
_MANIFEST_GID_RE = re.compile(r"^[0-9]{1,24}$")


def coerce_depot_id(value: object) -> Optional[str]:
    """Return a clean numeric AppID/DepotID string, or ``None`` if not valid.

    Rejects path separators, ``..``, whitespace and any non-digit character, so
    the result is always safe to interpolate into a path or config value.
    """
    if value is None:
        return None
    if isinstance(value, bool):  # bool is an int subclass; never a valid id
        return None
    if isinstance(value, int):
        text = str(value)
    elif isinstance(value, str):
        text = value.strip()
    else:
        return None
    return text if _DEPOT_ID_RE.match(text) else None


def coerce_manifest_gid(value: object) -> Optional[str]:
    """Return a clean numeric manifest GID string, or ``None`` if not valid."""
    if value is None:
        return None
    if isinstance(value, bool):
        return None
    text = str(value).strip() if isinstance(value, (str, int)) else ""
    return text if _MANIFEST_GID_RE.match(text) else None


def extract_token(content: str, appid: Optional[object] = None) -> Optional[str]:
    """Extract an ``addtoken`` value from a Lua, ignoring commented-out lines.

    The token is bound to ``appid`` when one is supplied. A bare ``\\d+`` would
    accept the first token in the file regardless of which app it belongs to and
    then file it under whatever AppID the caller inferred.
    """
    if not content:
        return None

    if appid is not None:
        aid = coerce_depot_id(appid)
        if aid:
            pattern = r'addtoken\s*\(\s*' + re.escape(aid) + r'\s*,\s*["\']([^"\']+)["\']\s*\)'
            match = find_live(content, pattern, re.IGNORECASE)
            if match:
                return match.group(1)
            return None

    match = find_live(
        content, r'addtoken\s*\(\s*[0-9]+\s*,\s*["\']([^"\']+)["\']\s*\)', re.IGNORECASE
    )
    return match.group(1) if match else None


def has_live_token(content: str, appid: Optional[object] = None) -> bool:
    """True when a non-commented ``addtoken`` statement exists."""
    if not content:
        return False
    if appid is not None:
        aid = coerce_depot_id(appid)
        if aid:
            return (
                find_live(
                    content,
                    r'addtoken\s*\(\s*' + re.escape(aid) + r'\s*,',
                    re.IGNORECASE,
                )
                is not None
            )
    return find_live(content, r"addtoken\s*\(\s*[0-9]+", re.IGNORECASE) is not None
